### ISSUE TITLE
Add ability to manually change the dates in changelogs

### ISSUE THREAD

**Issue by ryansrofe** [FormidableLabs/FigLog#64]
I see a critical issue with users trying to use FigLog with older manual made changelogs. I think it might be an important feature that I didn't want to add but can see the value in now. Maybe it can become a setting sort of  like locking. But it would be good for adoption if you already have a bunch of notes in a manual changelog and want to start using FigLog you can't alter the dates to match the original data. Maybe we add a setting that allows you to change the dates when activated and not when false.

**Comment by ryansrofe** [comment]
Adding this feature is a game changer for users adopting this widget with already existing changelogs. Without any way to change dates it's almost impossible to switch over to FigLog without sacrificing the original data (if dates were kept) and everything would have essentially the same date of entry.

Maybe not a deal breaker but certainly not ideal for teams that have taken the time to curate a changelog. Also other community libraries that could use our widget can start.

This could just be a setting that when turned on allows manual update of the date? When turned off date work as they do now. Off would be the default setting.

How do we deal with reordering when dates might change?

**Comment by cpresler** [comment]
I'm not sure about the import feature - I think it could be pretty cool, but I think it also might be super problematic in terms of formatting data and getting everything set to work inside of our data structure.

As far as how this works though, I'm wondering about something - I understand why the property menu setting is what makes sense for this particular features in silo, but knowing that we probably want to push toward a "editing" and "display" mode version of the logs, wouldn't it make more sense to create that "editing" toggle on individual change log template and have this be the first piece that uses that functionality?

I'm thinking that the "editing" state approach would allow us to enable more rich text via a basic markdown syntax, and help with locking logs so that they aren't accidentally changed.

**Comment by cpresler** [comment]
Creating a list of subtasks based on our conversations:
- [ ] design `editing` state and `display` state
- [ ] implement state change action
- [ ] build `display`
- [ ] build `editing`
   - [ ] input forms
   - [ ] validation on submit
- [ ] manual date entry
   - [ ] formatting text entered
   - [ ] validation & error states
- [ ] auto-sorting logs based on date updates
